version: "3.3"
services:
  api:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    links:
      - mysql:mysql
  mysql:
    restart: always
    image: mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: rZhUHJLYtW
      MYSQL_DATABASE: task
    volumes:
      - ~/mysql/datas:/var/lib/mysql