// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"task_manager/ent/hospital"

	"entgo.io/ent/dialect/sql"
)

// Hospital is the model entity for the Hospital schema.
type Hospital struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Hospital) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case hospital.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Hospital", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Hospital fields.
func (h *Hospital) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hospital.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			h.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Hospital.
// Note that you need to call Hospital.Unwrap() before calling this method if this Hospital
// was returned from a transaction, and the transaction was committed or rolled back.
func (h *Hospital) Update() *HospitalUpdateOne {
	return (&HospitalClient{config: h.config}).UpdateOne(h)
}

// Unwrap unwraps the Hospital entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (h *Hospital) Unwrap() *Hospital {
	_tx, ok := h.config.driver.(*txDriver)
	if !ok {
		panic("ent: Hospital is not a transactional entity")
	}
	h.config.driver = _tx.drv
	return h
}

// String implements the fmt.Stringer.
func (h *Hospital) String() string {
	var builder strings.Builder
	builder.WriteString("Hospital(")
	builder.WriteString(fmt.Sprintf("id=%v", h.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Hospitals is a parsable slice of Hospital.
type Hospitals []*Hospital

func (h Hospitals) config(cfg config) {
	for _i := range h {
		h[_i].config = cfg
	}
}
