// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"task_manager/ent/hospital"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HospitalCreate is the builder for creating a Hospital entity.
type HospitalCreate struct {
	config
	mutation *HospitalMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (hc *HospitalCreate) SetName(s string) *HospitalCreate {
	hc.mutation.SetName(s)
	return hc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (hc *HospitalCreate) SetNillableName(s *string) *HospitalCreate {
	if s != nil {
		hc.SetName(*s)
	}
	return hc
}

// SetAddress sets the "address" field.
func (hc *HospitalCreate) SetAddress(s string) *HospitalCreate {
	hc.mutation.SetAddress(s)
	return hc
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (hc *HospitalCreate) SetNillableAddress(s *string) *HospitalCreate {
	if s != nil {
		hc.SetAddress(*s)
	}
	return hc
}

// SetCreatedAt sets the "created_at" field.
func (hc *HospitalCreate) SetCreatedAt(t time.Time) *HospitalCreate {
	hc.mutation.SetCreatedAt(t)
	return hc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (hc *HospitalCreate) SetNillableCreatedAt(t *time.Time) *HospitalCreate {
	if t != nil {
		hc.SetCreatedAt(*t)
	}
	return hc
}

// SetUpdatedAt sets the "updated_at" field.
func (hc *HospitalCreate) SetUpdatedAt(t time.Time) *HospitalCreate {
	hc.mutation.SetUpdatedAt(t)
	return hc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (hc *HospitalCreate) SetNillableUpdatedAt(t *time.Time) *HospitalCreate {
	if t != nil {
		hc.SetUpdatedAt(*t)
	}
	return hc
}

// Mutation returns the HospitalMutation object of the builder.
func (hc *HospitalCreate) Mutation() *HospitalMutation {
	return hc.mutation
}

// Save creates the Hospital in the database.
func (hc *HospitalCreate) Save(ctx context.Context) (*Hospital, error) {
	var (
		err  error
		node *Hospital
	)
	hc.defaults()
	if len(hc.hooks) == 0 {
		if err = hc.check(); err != nil {
			return nil, err
		}
		node, err = hc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*HospitalMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = hc.check(); err != nil {
				return nil, err
			}
			hc.mutation = mutation
			if node, err = hc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(hc.hooks) - 1; i >= 0; i-- {
			if hc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = hc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, hc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Hospital)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from HospitalMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (hc *HospitalCreate) SaveX(ctx context.Context) *Hospital {
	v, err := hc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hc *HospitalCreate) Exec(ctx context.Context) error {
	_, err := hc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hc *HospitalCreate) ExecX(ctx context.Context) {
	if err := hc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (hc *HospitalCreate) defaults() {
	if _, ok := hc.mutation.Name(); !ok {
		v := hospital.DefaultName
		hc.mutation.SetName(v)
	}
	if _, ok := hc.mutation.Address(); !ok {
		v := hospital.DefaultAddress
		hc.mutation.SetAddress(v)
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		v := hospital.DefaultCreatedAt
		hc.mutation.SetCreatedAt(v)
	}
	if _, ok := hc.mutation.UpdatedAt(); !ok {
		v := hospital.DefaultUpdatedAt
		hc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hc *HospitalCreate) check() error {
	if _, ok := hc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Hospital.name"`)}
	}
	if v, ok := hc.mutation.Name(); ok {
		if err := hospital.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Hospital.name": %w`, err)}
		}
	}
	if _, ok := hc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Hospital.address"`)}
	}
	if v, ok := hc.mutation.Address(); ok {
		if err := hospital.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Hospital.address": %w`, err)}
		}
	}
	if _, ok := hc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Hospital.created_at"`)}
	}
	if _, ok := hc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Hospital.updated_at"`)}
	}
	return nil
}

func (hc *HospitalCreate) sqlSave(ctx context.Context) (*Hospital, error) {
	_node, _spec := hc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (hc *HospitalCreate) createSpec() (*Hospital, *sqlgraph.CreateSpec) {
	var (
		_node = &Hospital{config: hc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: hospital.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: hospital.FieldID,
			},
		}
	)
	if value, ok := hc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hospital.FieldName,
		})
		_node.Name = value
	}
	if value, ok := hc.mutation.Address(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: hospital.FieldAddress,
		})
		_node.Address = value
	}
	if value, ok := hc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hospital.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := hc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: hospital.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// HospitalCreateBulk is the builder for creating many Hospital entities in bulk.
type HospitalCreateBulk struct {
	config
	builders []*HospitalCreate
}

// Save creates the Hospital entities in the database.
func (hcb *HospitalCreateBulk) Save(ctx context.Context) ([]*Hospital, error) {
	specs := make([]*sqlgraph.CreateSpec, len(hcb.builders))
	nodes := make([]*Hospital, len(hcb.builders))
	mutators := make([]Mutator, len(hcb.builders))
	for i := range hcb.builders {
		func(i int, root context.Context) {
			builder := hcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HospitalMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hcb *HospitalCreateBulk) SaveX(ctx context.Context) []*Hospital {
	v, err := hcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hcb *HospitalCreateBulk) Exec(ctx context.Context) error {
	_, err := hcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hcb *HospitalCreateBulk) ExecX(ctx context.Context) {
	if err := hcb.Exec(ctx); err != nil {
		panic(err)
	}
}
