// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Hospital is the predicate function for hospital builders.
type Hospital func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)
